// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHzYihJ4fvs_VSSduvSETAwLK2KBhrW4',
    appId: '1:812204068382:web:0cc73ff6ba27f2c8c5e80f',
    messagingSenderId: '812204068382',
    projectId: 'chuck-461219',
    authDomain: 'chuck-461219.firebaseapp.com',
    storageBucket: 'chuck-461219.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG4HsiUuenv1Buxyhgwu0P5LSkt7qxYzw',
    appId: '1:812204068382:android:b3b5fec08d6bab33c5e80f',
    messagingSenderId: '812204068382',
    projectId: 'chuck-461219',
    storageBucket: 'chuck-461219.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOMuh2IYxDVAYQXJTQCFcsG544v22BuE4',
    appId: '1:812204068382:ios:81962799f6fe5924c5e80f',
    messagingSenderId: '812204068382',
    projectId: 'chuck-461219',
    storageBucket: 'chuck-461219.firebasestorage.app',
    iosClientId: '812204068382-um08huc1bk8turp9gm4i211jluqkvckf.apps.googleusercontent.com',
    iosBundleId: 'org.chernovia.googAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOMuh2IYxDVAYQXJTQCFcsG544v22BuE4',
    appId: '1:812204068382:ios:81962799f6fe5924c5e80f',
    messagingSenderId: '812204068382',
    projectId: 'chuck-461219',
    storageBucket: 'chuck-461219.firebasestorage.app',
    iosClientId: '812204068382-um08huc1bk8turp9gm4i211jluqkvckf.apps.googleusercontent.com',
    iosBundleId: 'org.chernovia.googAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxHzYihJ4fvs_VSSduvSETAwLK2KBhrW4',
    appId: '1:812204068382:web:77d2a3c732b97edac5e80f',
    messagingSenderId: '812204068382',
    projectId: 'chuck-461219',
    authDomain: 'chuck-461219.firebaseapp.com',
    storageBucket: 'chuck-461219.firebasestorage.app',
  );
}
